import { pgTable, text, integer, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const settingsTable = pgTable('settings', {
  id: text('id').primaryKey().default('default'),
  botToken: text('bot_token'),
  destinationChannel: text('destination_channel'),
  adminPasswordHash: text('admin_password_hash').default('admin123'),
  isMonitoringPaused: boolean('is_monitoring_paused').default(false),
  isVerified: boolean('is_verified').default(false),
  globalKeywords: jsonb('global_keywords'),
  globalForbiddenKeywords: jsonb('global_forbidden_keywords'),
  enableGlobalKeywords: boolean('enable_global_keywords').default(false),
  globalKeywordMatchMode: text('global_keyword_match_mode').default('any'),
  rateLimits: jsonb('rate_limits'),
  panelConfig: jsonb('panel_config'),
  forwardingSettings: jsonb('forwarding_settings'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const telegramClientTable = pgTable('telegram_client', {
  id: text('id').primaryKey().default('default'),
  apiId: integer('api_id'),
  apiHash: text('api_hash'),
  phoneNumber: text('phone_number'),
  connectedPhone: text('connected_phone'),
  telegramSession: text('telegram_session'),
  isClientConnected: boolean('is_client_connected').default(false),
  isMonitoringPaused: boolean('is_monitoring_paused').default(false),
  lastConnectedAt: text('last_connected_at'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const telegramAccountsTable = pgTable('telegram_accounts', {
  id: text('id').primaryKey(),
  phoneNumber: text('phone_number'),
  telegramSession: text('telegram_session'),
  isConnected: boolean('is_connected').default(false),
  accountName: text('account_name'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const sourcesTable = pgTable('sources', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  name: text('name'),
  username: text('username'),
  type: text('type').default('channel'),
  status: text('status').default('active'),
  isChannel: boolean('is_channel').default(true),
  isActive: boolean('is_active').default(true),
  lastCheckedAt: text('last_checked_at'),
  lastMessageId: integer('last_message_id').default(0),
  totalTransferred: integer('total_transferred').default(0),
  errorMessage: text('error_message'),
  createdAt: text('created_at'),
  avatarUrl: text('avatar_url'),
  subscriberCount: text('subscriber_count'),
  numericId: text('numeric_id'),
  keywords: jsonb('keywords'),
  enableKeywords: boolean('enable_keywords').default(false),
  keywordMatchMode: text('keyword_match_mode').default('any'),
  keywordFilter: jsonb('keyword_filter'),
  contentCleaner: jsonb('content_cleaner'),
  signature: text('signature'),
  cleaningRules: jsonb('cleaning_rules'),
  footerText: text('footer_text'),
  contactSettings: jsonb('contact_settings'),
  mediaSettings: jsonb('media_settings'),
  aiSettings: jsonb('ai_settings'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const statisticsTable = pgTable('statistics', {
  id: text('id').primaryKey().default('default'),
  totalTransferred: integer('total_transferred').default(0),
  failedMessages: integer('failed_messages').default(0),
  startTime: text('start_time'),
  lastBackupTime: text('last_backup_time'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const logsTable = pgTable('logs', {
  id: text('id').primaryKey(),
  timestamp: text('timestamp').notNull(),
  type: text('type').default('info'),
  text: text('text').default(''),
  sourceId: text('source_id'),
  sourceUsername: text('source_username'),
  sourceTitle: text('source_title'),
  channelName: text('channel_name'),
  messageId: integer('message_id').default(0),
  contentType: text('content_type').default('text'),
  mediaType: text('media_type').default(''),
  status: text('status').notNull().default('success'),
  details: text('details').default(''),
  destinationChannel: text('destination_channel'),
  isFiltered: boolean('is_filtered').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

export const aiProcessingTable = pgTable('ai_processing', {
  id: text('id').primaryKey().default('default'),
  enableAiProcessing: boolean('enable_ai_processing').default(true),
  enabled: boolean('enabled').default(true),
  apiKey: text('api_key'),
  model: text('model').default('self-hosted'),
  customPrompt: text('custom_prompt'),
  translateToPersian: boolean('translate_to_persian').default(false),
  sanitizeText: boolean('sanitize_text').default(true),
  summarize: boolean('summarize').default(false),
  extractKeywords: boolean('extract_keywords').default(false),
  formatMarkdown: boolean('format_markdown').default(true),
  style: text('style').default('default'),
  targetLanguage: text('target_language').default('fa'),
  enableKeywordFilter: boolean('enable_keyword_filter').default(false),
  allowedKeywords: jsonb('allowed_keywords'),
  blockedKeywords: jsonb('blocked_keywords'),
  keywordMatchMode: text('keyword_match_mode').default('any'),
  messagesPassed: integer('messages_passed').default(0),
  messagesBlocked: integer('messages_blocked').default(0),
  enableContentCleaning: boolean('enable_content_cleaning').default(false),
  cleaningRules: jsonb('cleaning_rules'),
  removeTelegramLinks: boolean('remove_telegram_links').default(true),
  removeInstagramLinks: boolean('remove_instagram_links').default(true),
  removeAllUrls: boolean('remove_all_urls').default(false),
  removeUsernames: boolean('remove_usernames').default(true),
  removeHashtags: boolean('remove_hashtags').default(true),
  removeEmojis: boolean('remove_emojis').default(false),
  aiRewriteEnabled: boolean('ai_rewrite_enabled').default(false),
  enableAiRewrite: boolean('enable_ai_rewrite').default(false),
  aiRewriteStyle: text('ai_rewrite_style').default('formal_news'),
  aiRewriteIntensity: text('ai_rewrite_intensity').default('medium'),
  aiRewriteCustomPrompt: text('ai_rewrite_custom_prompt'),
  aiRewriteMaxLength: integer('ai_rewrite_max_length').default(2000),
  writingStyle: text('writing_style').default('professional'),
  customWritingStyle: text('custom_writing_style'),
  enableContactManager: boolean('enable_contact_manager').default(false),
  defaultContactNote: text('default_contact_note'),
  enableMediaControl: boolean('enable_media_control').default(false),
  forwardPhotos: boolean('forward_photos').default(true),
  forwardVideos: boolean('forward_videos').default(true),
  forwardPdfs: boolean('forward_pdfs').default(true),
  forwardDocuments: boolean('forward_documents').default(true),
  forwardAudios: boolean('forward_audios').default(true),
  mediaOrder: text('media_order').default('media_first'),
  enableDuplicateProtection: boolean('enable_duplicate_protection').default(false),
  duplicateDetectionType: text('duplicate_detection_type').default('both'),
  timeWindowHours: integer('time_window_hours').default(1),
  maxForwardingCount: integer('max_forwarding_count').default(2),
  enableJobExtraction: boolean('enable_job_extraction').default(false),
  enableMessageSignature: boolean('enable_message_signature').default(false),
  signatureText: text('signature_text'),
  addSignatureAfterEveryMessage: boolean('add_signature_after_every_message').default(true),
  promptTemplates: jsonb('prompt_templates'),
  wordFilters: jsonb('word_filters'),
  replaceWords: jsonb('replace_words'),
  blacklist: jsonb('blacklist'),
  whitelist: jsonb('whitelist'),
  contactSettings: jsonb('contact_settings'),
  forwardingSettings: jsonb('forwarding_settings'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const duplicateCacheTable = pgTable('duplicate_cache', {
  id: text('id').primaryKey(),
  sourceId: text('source_id'),
  messageId: integer('message_id'),
  messageHash: text('message_hash').notNull(),
  channelId: text('channel_id'),
  timestamp: timestamp('timestamp').defaultNow(),
});

export const cleaningRulesTable = pgTable('cleaning_rules', {
  id: text('id').primaryKey(),
  pattern: text('pattern').notNull(),
  replaceWith: text('replace_with').default(''),
  type: text('type').default('remove'),
  isActive: boolean('is_active').default(true),
  scope: text('scope').default('global'),
  channelId: text('channel_id'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const messageSignatureTable = pgTable('message_signature', {
  id: text('id').primaryKey().default('default'),
  enabled: boolean('enabled').default(false),
  signatureText: text('signature_text'),
  position: text('position').default('bottom'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const contactSettingsTable = pgTable('contact_settings', {
  id: text('id').primaryKey().default('default'),
  removeUsernames: boolean('remove_usernames').default(true),
  removeLinks: boolean('remove_links').default(true),
  removePhones: boolean('remove_phones').default(true),
  customReplacements: jsonb('custom_replacements'),
  updatedAt: timestamp('updated_at').defaultNow(),
});
